modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="utopiacore"
version="0.0.1"
displayName="Utopia Core"
authors="Arp"
description="Core mod of the pack Create Building Utopia."


[[dependencies.utopiacore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.utopiacore]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.7,)"
    ordering="NONE"
    side="BOTH"